### ISSUE TITLE
Konflikt Obserwowania

### ISSUE THREAD

**Issue by skandaI** [Kurahen-Premium/Kurahen-Premium#45]
Sprawa jest następująca: zaimportowaliśmy z Twojego skryptu cały moduł do obserwowania tematów i mamy kuca, który może go dalej rozwijać, lecz zachodzi tutaj konflikt polegający na tym, że wielu anonów używa obserwowania dołączonego do userscriptu zamiast tego samego, który jest już standardowo w kodzie strony, przez co wprowadzone zmiany obejmowałyby tylko część użytkowników. W związku z tym widzę dwa sensowne wyjścia:
1. Synchronizujemy stale wszystkie wprowadzone zmiany między tymi dwoma modułami.
2. Usuwasz moduł obserwowania z Kurahen-Premium i tworzysz oddzielne repozytorium, w którym wspólnie go rozwijamy i potem aktualizujemy na serwerze Karachana.

Co o tym sądzisz?

**Comment by yeon-boy** [comment]
@skandaI Własnie chyba kurwa im wymusiłeś aktualizację xD

**Comment by skandaI** [comment]
Widzisz, jak się chce, to można. xD Also ten watcher jest jakoś połowicznie wywalony, bo jak się klika "Pobierz wersję stabilną", to cały czas tam jest.

**Comment by yeon-boy** [comment]
Nic jeszcze nie zostało wywalone - patrz #47

**Comment by yeon-boy** [comment]
@skandaI Już wywalone.

Tylko weź zaktualizuj w Mitsubie Obserwatora Nitek na tego stąd https://github.com/Kurahen-Premium/Threads-watcher/releases/tag/v1.0.0
bo widzę że na kara nadal jest jakaś stara wersja z listopada.

**Comment by skandaI** [comment]
Przydałby się tu jeszcze update README.md, bo na tę chwilę nieco wprowadza w błąd.

**Comment by yeon-boy** [comment]
OK, poprawię go.

**Comment by yeon-boy** [comment]
Zrobione.

BTW: Liczę że aktualizacje kodu obserwatora nitek na serwerze produkcyjnym w przyszłości jednak będą pojawiać się żwawiej niż obecnie, bo inaczej to przykro.
Nawet bym mógł robić PR do repo Mitsuby z tym co trzeba podmienić, ale widzę że to co jest pod https://github.com/karachan/Mitsuba jest zdecydowanie nieaktualne. Wycofaliście się z prowadzenia publicznego repo?

**Comment by skandaI** [comment]
Tak, zanurzyliśmy repo. Nasz kuc ma teraz chyba inne priorytety W tej nowszej wersji Obserwatora jest w ogóle coś istotnego?

**Comment by yeon-boy** [comment]
Masz tu diff: https://www.diffchecker.com/4cnrid7c

Zasadniczo jest przywrócony poprawny styl przycisku `[Obserwuj]`, który na własną rękę zmieniliście próbując wyciąć kod tak zeby działał, oraz pozbyto się zmiennej globalnej `hideThreadsWithNoNewPosts` - teraz jest lokalna dla obiektu `ThreadsWatcher`.

Drobne zmiany, ale sympatyczne. Pytałem o szybkość aktualizacji bardziej na przyszłość.

**Comment by skandaI** [comment]
Jak chcesz, to mogę Ci dać dostęp do aktualnego repo Mitsuby, tylko musiałbyś sobie założyć konto na Bitbucket. Jakbyś tam wrzucał poprawki, to stamtąd by już szło szybko na serwer.

**Comment by yeon-boy** [comment]
OK, zawsze to łatwiej zgłaszać bugi

https://bitbucket.org/yeon_boy

**Comment by yeon-boy** [comment]
sądzę że poziom uprawnień 'WRITE' by chyba wystarczył, jak każda jedna osoba ma 'ADMIN', to łatwiej coś bardzo popsuć - celowo lub przypadkiem

**Comment by skandaI** [comment]
Zmieniłem. Also nasz kuc coś tam wspominał o drastycznym przebudowaniu (albo wręcz napisaniu go od nowa z wykorzystaniem fragmentów kodu tego aktualnego) Obserwatora w celu, jak to określił, lepszej integracji.

**Comment by yeon-boy** [comment]
Lepszej integracji z czym? Z kodem HTML i stylem strony, mówiąc o przyciskach [obserwuj] oraz ramce na listę obserwowanych nitek? No to może i warto to i owo poprawić, pisane to było przy założeniu braku współpracy z istniejącą stroną.

Bo sam mechanizm pobierania/zapisywania obserwowanych chyba trudno 'bardziej zintegrować'.

**Comment by skandaI** [comment]
Będę musiał się dopytać, kiedy się zjawi. Spytałem go wtedy, czy przez "lepszą integrację" ma na myśli, że będzie to też w jakiś sposób wydajniejsze i odpowiedział "to na pewno".

**Comment by yeon-boy** [comment]
Ooo, no to może chodziło mu o wreszcie trzymanie listy obserwowanych po stronie serwera, jak kiedyś, wtedy pobranie jej to byłoby 1 zapytanie, a nie tyle zapytań ile nitek w obserwowanych. To aprobowałbym bardzo, ale wymaga to własnie owej integracji i kodu PHP również.

**Comment by skandaI** [comment]
Sorry, musiałem Cię jednak wyjebać z Bitbucket, bo na darmowym koncie jest limit 5 osób na prywatne repo, a doszedł nam jeszcze jeden kuc, który ma ambicje dużo robić.

**Comment by yeon-boy** [comment]
Wystarczy że właściciel repo potwierdzi w ustawieniach konta dowolny e-mail w domenie `*.edu` lub `*.edu.pl` i wtedy dostajesz konto bez limitu osób za darmo. Same kuce to chyba ktoś studiuje? xD

Gdzieś po internecie jak pamiętam są serwisy w tych domenach z darmową pocztą. Ewentualnie taką domenę można sobie po prostu kupić, może też zadziała.

**Comment by skandaI** [comment]
Spróbuję to załatwić.

**Comment by skandaI** [comment]
Już ogarnięte. Dodałem.

**Comment by yeon-boy** [comment]
[cool]

**Comment by skandaI** [comment]
Po ostatniej aktualizacji Mitsuby coś się zjebało z obserwowaniem, bo z poziomu boardu dodaje cały czas +1 do liczby nieprzeczytanych postów. O tyle dziwne, że sam Obserwator nie był ruszany. Może szybciej ogarniesz co tu się stało.

**Comment by yeon-boy** [comment]
@skandaI było to zgłosić do repo Obserwatora
https://github.com/Kurahen-Premium/Threads-watcher/issues/6
rzucę na to okiem
